version: "3.7"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        command: ./docker-entrypoint.sh -- python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DJANGO_SETTINGS_MODULE=upwork_exam.settings.prod
        depends_on:
            - db
    db:
        image: postgres:14-alpine
        volumes:
          - upwork_exam_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:5432

volumes:
    upwork_exam_db:
