# Generated by Django 4.2 on 2023-12-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_liked_by",
            field=models.ManyToManyField(
                null=True,
                related_name="favorite_profiles",
                to="authentication.customer",
            ),
        ),
    ]
